import { Injectable, signal } from '@angular/core';
import { environment } from '../../environments/environment';
import { HttpClient } from '@angular/common/http';


export interface Note {
  id: string;
  titulo: string;
  contenido: string;
  fechaCreacion: string;
  fechaActualizacion: string;
  isTitleManuallySet?: boolean;
  isTitleAutoGenerated?: boolean;
  isSavedInDB?: boolean;
}

@Injectable({
  providedIn: 'root'
})
export class NoteService {
  notes = signal<Note[]>([]);
  activeNoteId = signal<string | null>(null);

  constructor(private http: HttpClient) {
     this.loadNotesFromFirebase();
  }
  loadNotesFromFirebase() {

  const url = `${environment.firebaseUrl}.json`;

  this.http.get<{ [key: string]: Note }>(url).subscribe({

    next: (data) => {

      if (!data) {
        this.createNote();
        return;
      }

     const firebaseNotes = Object.values(data).map(note => ({
      
  ...note,
  isSavedInDB: true,
  isTitleManuallySet: note.titulo !== 'Untitled Document',
  isTitleAutoGenerated: false
}));
this.notes.set(firebaseNotes);

this.activeNoteId.set(firebaseNotes[0].id);
    },

    error: (err) => {
      console.error(' Error cargando notas:', err);
    }

  });

}

  createNote() {
    const emptyNote = this.notes().find(n => n.titulo === 'Untitled Document' && n.contenido.trim() === '');
    
    if (emptyNote) {
      if (this.activeNoteId() !== emptyNote.id) {
        this.setActiveNote(emptyNote.id);
      }
      return; 
    }

    const newNote: Note = {
      id: crypto.randomUUID(), 
      titulo: 'Untitled Document',
      contenido: '',
      fechaCreacion: new Date().toISOString(),
      fechaActualizacion: new Date().toISOString(),
      isTitleManuallySet: false,
      isTitleAutoGenerated: false,
      isSavedInDB: false 
    };
    
    this.notes.update(currentNotes => [...currentNotes, newNote]);
    this.activeNoteId.set(newNote.id);
  }

  setActiveNote(id: string) {
    this.activeNoteId.set(id);
  }

  getActiveNote(): Note | undefined {
    return this.notes().find(n => n.id === this.activeNoteId());
  }

  updateActiveNoteContent(content: string) {
    const currentId = this.activeNoteId();
    if (!currentId) return;

    this.notes.update(currentNotes => 
      currentNotes.map(note => 
        note.id === currentId 
          ? { ...note, contenido: content, fechaActualizacion: new Date().toISOString() } 
          : note
      )
    );
  }

  updateActiveNoteTitle(title: string) {
    const currentId = this.activeNoteId();
    if (!currentId) return;

    const newTitle = title.trim() === '' ? 'Untitled Document' : title.trim();

    this.notes.update(currentNotes => 
      currentNotes.map(note => 
        note.id === currentId 
          ? { 
              ...note, 
              titulo: newTitle, 
              fechaActualizacion: new Date().toISOString(),
              isTitleManuallySet: newTitle !== 'Untitled Document' 
            } 
          : note
      )
    );

    this.simulateFirebaseSave(currentId);
  }

  // guardar titulos de docs
  handleAFKState(content: string) {
    const active = this.getActiveNote();
    if (!active) return;

    let newTitle = active.titulo;
    let autoGeneratedNow = active.isTitleAutoGenerated;

    if (!active.isTitleManuallySet && !active.isTitleAutoGenerated) {
      const cleanContent = content
        .replace(/<[^>]*>?/gm, ' ')
        .replace(/&nbsp;/gi, ' ')
        .replace(/\s+/g, ' ')
        .trim();
      
      if (cleanContent.length > 0) {
        newTitle = cleanContent.substring(0, 30).trim();
        autoGeneratedNow = true;
      }
    }

    this.notes.update(currentNotes => 
      currentNotes.map(note => 
        note.id === active.id 
          ? { ...note, titulo: newTitle, isTitleAutoGenerated: autoGeneratedNow } 
          : note
      )
    );

    this.simulateFirebaseSave(active.id);
  }

  deleteNote(id: string) {
    const url = `${environment.firebaseUrl}/${id}.json`;

this.http.delete(url).subscribe({

  next: () => {
    console.log('Nota eliminada de Firebase');
  },

  error: (err) => {
    console.error('Error eliminando nota:', err);
  }

});
    this.notes.update(currentNotes => currentNotes.filter(note => note.id !== id));
    const remainingNotes = this.notes();
    // siempre habrá una nota
    if (remainingNotes.length === 0) {
      this.createNote();
    } else if (this.activeNoteId() === id) {
      this.activeNoteId.set(remainingNotes[0].id);
    }
  }

  // =========================================================================================
  // TUTORIAL - MIGRACIÓN A FIREBASE REALTIME DATABASE (REST API)
  // =========================================================================================
  /*
    PASOS PARA IMPLEMENTAR FIREBASE (Según las reglas de tu PDF):
    1. En 'app.config.ts', agrega 'provideHttpClient()'.
    2. Importa 'HttpClient' aquí: `import { HttpClient } from '@angular/common/http';`
    3. Inyéctalo en el constructor: `constructor(private http: HttpClient) { this.createNote(); }`
    4. Crea un environment en `src/environments/environment.ts` con la URL de tu base de datos:
       ej: `firebaseUrl: 'https://TU-PROYECTO.firebaseio.com/notas'`
    
    PARA DESCOMENTAR Y USAR LA LÓGICA REAL:
    Cuando lo integres, cambia el contenido de 'simulateFirebaseSave' por la lógica que está
    comentada abajo, y BORRA los console.log de simulación.
    */
    simulateFirebaseSave(id: string) {const noteToSave = this.notes().find(n => n.id === id);
      

  if (!noteToSave) return;
  const firebaseNote = {
  id: noteToSave.id,
  titulo: noteToSave.titulo,
  contenido: noteToSave.contenido,
  fechaCreacion: noteToSave.fechaCreacion,
  fechaActualizacion: noteToSave.fechaActualizacion
};

  // Evitar guardar notas vacías
  if (!noteToSave.isTitleManuallySet && noteToSave.contenido.trim() === '') {
    return;
  }

  const url = `${environment.firebaseUrl}/${noteToSave.id}.json`;

  // CREATE
  if (!noteToSave.isSavedInDB) {

    this.http.put(url, firebaseNote).subscribe({

    next: () => {

      console.log('✅ Nota creada en Firebase');

      this.notes.update(notes =>
        notes.map(n =>
          n.id === id
            ? { ...n, isSavedInDB: true }
            : n
        )
      );

    },

    error: (err) => {
      console.error('❌ Error creando nota:', err);
    }

  });

}

// UPDATE
else {

  this.http.patch(url, {

    titulo: noteToSave.titulo,
    contenido: noteToSave.contenido,
    fechaActualizacion: noteToSave.fechaActualizacion

  }).subscribe({

    next: () => {
      console.log('🔄 Nota actualizada');
    },

    error: (err) => {
      console.error('❌ Error actualizando:', err);
    }

  });

}

    /*
    // --- LÓGICA FIREBASE REAL (REST API) - DESCOMENTAR LUEGO ---
    const url = `https://TU-PROYECTO.firebaseio.com/notas/${noteToSave.id}.json`;

    if (!noteToSave.isSavedInDB) {
      // POST no es recomendable con IDs personalizados, en REST de Firebase es mejor usar PUT 
      // para que Firebase respete el ID 'crypto.randomUUID()' que ya generaste.
      this.http.put(url, noteToSave).subscribe({
        next: () => this.notes.update(notes => notes.map(n => n.id === id ? { ...n, isSavedInDB: true } : n)),
        error: (err) => console.error('Error al crear', err)
      });
    } else {
      // Si ya existe, hacemos un PUT o PATCH para actualizarlo
      this.http.patch(url, { 
        titulo: noteToSave.titulo, 
        contenido: noteToSave.contenido,
        fechaActualizacion: noteToSave.fechaActualizacion 
      }).subscribe();
    }
    */
  }
}