import { Injectable, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../environments/environment';

export interface Note {
  id: string;
  titulo: string;
  contenido: string;
  fechaCreacion: string;
  fechaActualizacion: string;
  titulodocManualmente?: boolean;
  titulodocGenerado?: boolean;
  guardadoenDB?: boolean;
}

@Injectable({
  providedIn: 'root'
})
export class NoteService {
  notes = signal<Note[]>([]);
  IdnotaActiva = signal<string | null>(null);
  
  cargandoenUI = signal<boolean>(true);
  
  syncStatus = signal<'Guardado en la nube' | 'Guardando...' | 'Error '>('Guardado en la nube');

  constructor(private http: HttpClient) {
     this.cargarnotasFirebase();
  }

  cargarnotasFirebase() {
    const url = `${environment.firebaseUrl}.json`;

    this.http.get<{ [key: string]: Note }>(url).subscribe({
      next: (data) => {
        if (!data) {
          this.crearunaNota();
          this.cargandoenUI.set(false);
          return;
        }

        const firebaseNotes = Object.values(data).map(note => ({
          ...note,
          guardadoenDB: true,
          titulodocManualmente: note.titulo !== 'Untitled Document',
          titulodocGenerado: note.titulo !== 'Untitled Document'
        }));

        firebaseNotes.sort((a, b) => new Date(b.fechaActualizacion).getTime() - new Date(a.fechaActualizacion).getTime());

        this.notes.set(firebaseNotes);
        this.IdnotaActiva.set(firebaseNotes[0].id);
        this.cargandoenUI.set(false);
      },
      error: (err) => {
        this.crearunaNota(); 
        this.cargandoenUI.set(false);
      }
    });
  }

  //crud
  crearunaNota() {
    const emptyNote = this.notes().find(n => n.titulo === 'Untitled Document' && n.contenido.trim() === '');
    
    if (emptyNote) {
      if (this.IdnotaActiva() !== emptyNote.id) {
        this.setActiveNote(emptyNote.id);
      }
      return; 
    }

    const newNote: Note = {
      id: crypto.randomUUID(), 
      titulo: 'Untitled Document',
      contenido: '',
      fechaCreacion: new Date().toISOString(),
      fechaActualizacion: new Date().toISOString(),
      titulodocManualmente: false,
      titulodocGenerado: false,
      guardadoenDB: false
    };
    
    this.notes.update(currentNotes => [newNote, ...currentNotes]);
    this.IdnotaActiva.set(newNote.id);
  }

  setActiveNote(id: string) {
    this.IdnotaActiva.set(id);
  }

  getActiveNote(): Note | undefined {
    return this.notes().find(n => n.id === this.IdnotaActiva());
  }

  updateActiveNoteContent(content: string) {
    const currentId = this.IdnotaActiva();
    if (!currentId) return;

    this.notes.update(currentNotes => 
      currentNotes.map(note => 
        note.id === currentId 
          ? { ...note, contenido: content, fechaActualizacion: new Date().toISOString() } 
          : note
      )
    );
  }

  updateActiveNoteTitle(title: string) {
    const currentId = this.IdnotaActiva();
    if (!currentId) return;

    const newTitle = title.trim() === '' ? 'Untitled Document' : title.trim();

    this.notes.update(currentNotes => 
      currentNotes.map(note => 
        note.id === currentId 
          ? { 
              ...note, 
              titulo: newTitle, 
              fechaActualizacion: new Date().toISOString(),
              titulodocManualmente: newTitle !== 'Untitled Document'
            } 
          : note
      )
    );

    this.guardarenFirebase(currentId);
  }

  handleAFKState(content: string) {
    const active = this.getActiveNote();
    if (!active) return;

    let newTitle = active.titulo;
    let autoGeneratedNow = active.titulodocGenerado;

    if (!active.titulodocManualmente && !active.titulodocGenerado) {
      const cleanContent = content
        .replace(/<[^>]*>?/gm, ' ')
        .replace(/&nbsp;/gi, ' ')
        .replace(/\s+/g, ' ')
        .trim();
      
      if (cleanContent.length > 0) {
        newTitle = cleanContent.substring(0, 30).trim();
        autoGeneratedNow = true;
      }
    }

    this.notes.update(currentNotes => 
      currentNotes.map(note => 
        note.id === active.id 
          ? { ...note, titulo: newTitle, titulodocGenerado: autoGeneratedNow } // FIX: Españolizado
          : note
      )
    );

    this.guardarenFirebase(active.id);
  }

  borrarNota(id: string) {
    const url = `${environment.firebaseUrl}/${id}.json`;
    this.syncStatus.set('Guardando...');
    
    this.http.delete(url).subscribe({
      next: () => {
        this.syncStatus.set('Guardado en la nube');
      },
      error: (err) => {
        console.error('Error eliminando nota:', err);
        this.syncStatus.set('Error ');
      }
    });

    this.notes.update(currentNotes => currentNotes.filter(note => note.id !== id));
    const remainingNotes = this.notes();
    
    if (remainingNotes.length === 0) {
      this.crearunaNota();
    } else if (this.IdnotaActiva() === id) {
      this.IdnotaActiva.set(remainingNotes[0].id);
    }
  }

  guardarenFirebase(id: string) {
    const noteToSave = this.notes().find(n => n.id === id);
    if (!noteToSave) return;

    if (!noteToSave.titulodocManualmente && noteToSave.contenido.trim() === '') {
      return; 
    }

    const firebaseNote = {
      id: noteToSave.id,
      titulo: noteToSave.titulo,
      contenido: noteToSave.contenido,
      fechaCreacion: noteToSave.fechaCreacion,
      fechaActualizacion: noteToSave.fechaActualizacion
    };

    const url = `${environment.firebaseUrl}/${noteToSave.id}.json`;

    this.syncStatus.set('Guardando...');

    if (!noteToSave.guardadoenDB) {
      this.http.put(url, firebaseNote).subscribe({
        next: () => {
          this.syncStatus.set('Guardado en la nube'); // AVISAMOS A LA UI QUE TERMINÓ
          
          this.notes.update(notes =>
            notes.map(n => n.id === id ? { ...n, guardadoenDB: true } : n)
          );
        },
        error: (err) => {
          console.error('Error creando nota:', err);
          this.syncStatus.set('Error ');
        }
      });
    } 
    else {
      this.http.patch(url, {
        titulo: noteToSave.titulo,
        contenido: noteToSave.contenido,
        fechaActualizacion: noteToSave.fechaActualizacion
      }).subscribe({
        next: () => {
          this.syncStatus.set('Guardado en la nube');
        },
        error: (err) => {
          console.error('Error actualizando:', err);
          this.syncStatus.set('Error ');
        }
      });
    }
  }
}